
import { OrderStatus, ShopInfo } from './types';
import type { Customer, Measurement, Order, LineItem, Payment, GarmentTypeDefinition, Employee } from './types';

export const LOCALES: Record<string, Record<string, string>> = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Orders',
    'nav.customers': 'Customers',
    'nav.employees': 'Employees',
    'nav.settings': 'Settings',
    'dashboard.title': 'Dashboard',
    'kpi.activeOrders': 'Active Orders',
    'kpi.dueToday': 'Due Today',
    'kpi.revenueMonth': 'Revenue (This Month)',
    'kpi.completedMonth': 'Completed (This Month)',
    'orders.title': 'Orders',
    'orders.inProgress': 'In Progress',
    'orders.pending': 'Pending',
    'orders.completed': 'Completed',
    'orders.delivered': 'Delivered',
    'orders.cancelled': 'Cancelled',
    'orders.all': 'All',
    'orders.newOrder': 'New Order',
    'order.order': 'Order',
    'order.customer': 'Customer',
    'order.dueDate': 'Due Date',
    'order.total': 'Total',
    'order.balance': 'Balance',
    'order.status': 'Status',
    'customers.title': 'Customers',
    'customers.newCustomer': 'New Customer',
    'customers.name': 'Name',
    'customers.phone': 'Phone',
    'customers.address': 'Address',
    'employees.title': 'Employees',
    'employees.newEmployee': 'New Employee',
    'employees.editEmployee': 'Edit Employee',
    'employees.name': 'Employee Name',
    'employees.role': 'Role',
    'form.save': 'Save',
    'form.cancel': 'Cancel',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',
    'login.title': 'Login to your Account',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.rememberMe': 'Remember Me',
    'login.button': 'Login',
    'login.error': 'Invalid username or password.',
    'settings.logout': 'Logout',
    'settings.logout.confirm': 'Are you sure you want to log out?',
  },
  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.orders': 'ऑर्डर',
    'nav.customers': 'ग्राहक',
    'nav.employees': 'कर्मचारी',
    'nav.settings': 'सेटिंग्स',
    'dashboard.title': 'डैशबोर्ड',
    'kpi.activeOrders': 'सक्रिय ऑर्डर',
    'kpi.dueToday': 'आज देय',
    'kpi.revenueMonth': 'राजस्व (इस महीने)',
    'kpi.completedMonth': 'पूर्ण (इस महीने)',
    'orders.title': 'ऑर्डर',
    'orders.inProgress': 'प्रगति में',
    'orders.pending': 'लंबित',
    'orders.completed': 'पूर्ण',
    'orders.delivered': 'डिलीवर',
    'orders.cancelled': 'रद्द',
    'orders.all': 'सभी',
    'orders.newOrder': 'नया ऑर्डर',
    'order.order': 'ऑर्डर',
    'order.customer': 'ग्राहक',
    'order.dueDate': 'नियत तारीख',
    'order.total': 'कुल',
    'order.balance': 'शेष',
    'order.status': 'स्थिति',
    'customers.title': 'ग्राहक',
    'customers.newCustomer': 'नया ग्राहक',
    'customers.name': 'नाम',
    'customers.phone': 'फ़ोन',
    'customers.address': 'पता',
    'employees.title': 'कर्मचारी',
    'employees.newEmployee': 'नया कर्मचारी',
    'employees.editEmployee': 'कर्मचारी संपादित करें',
    'employees.name': 'कर्मचारी का नाम',
    'employees.role': 'भूमिका',
    'form.save': 'सहेजें',
    'form.cancel': 'रद्द करें',
    'settings.title': 'सेटिंग्स',
    'settings.language': 'भाषा',
    'settings.theme': 'थीम',
    'settings.theme.light': 'लाइट',
    'settings.theme.dark': 'डार्क',
    'login.title': 'अपने खाते में પ્રવેશ करें',
    'login.username': 'उपयोगकर्ता नाम',
    'login.password': 'पासवर्ड',
    'login.rememberMe': 'मुझे याद रखें',
    'login.button': 'लॉग इन करें',
    'login.error': 'अमान्य उपयोगकर्ता नाम या पासवर्ड।',
    'settings.logout': 'लॉग आउट',
    'settings.logout.confirm': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
  },
  mr: {
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.orders': 'ऑर्डर्स',
    'nav.customers': 'ग्राहक',
    'nav.employees': 'कर्मचारी',
    'nav.settings': 'सेटिंग्ज',
    'dashboard.title': 'डॅशबोर्ड',
    'kpi.activeOrders': 'सक्रिय ऑर्डर्स',
    'kpi.dueToday': 'आज देय',
    'kpi.revenueMonth': 'महसूल (या महिन्यात)',
    'kpi.completedMonth': 'पूर्ण (या महिन्यात)',
    'orders.title': 'ऑर्डर्स',
    'orders.inProgress': 'प्रगतीपथावर',
    'orders.pending': 'प्रलंबित',
    'orders.completed': 'पूर्ण',
    'orders.delivered': 'डिलिव्हर',
    'orders.cancelled': 'रद्द',
    'orders.all': 'सर्व',
    'orders.newOrder': 'नवीन ऑर्डर',
    'order.order': 'ऑर्डर',
    'order.customer': 'ग्राहक',
    'order.dueDate': 'देय तारीख',
    'order.total': 'एकूण',
    'order.balance': 'शिल्लक',
    'order.status': 'स्थिती',
    'customers.title': 'ग्राहक',
    'customers.newCustomer': 'नवीन ग्राहक',
    'customers.name': 'नाव',
    'customers.phone': 'फोन',
    'customers.address': 'पत्ता',
    'employees.title': 'कर्मचारी',
    'employees.newEmployee': 'नवीन कर्मचारी',
    'employees.editEmployee': 'कर्मचारी संपादित करा',
    'employees.name': 'कर्मचाऱ्याचे नाव',
    'employees.role': 'भूमिका',
    'form.save': 'जतन करा',
    'form.cancel': 'रद्द करा',
    'settings.title': 'सेटिंग्ज',
    'settings.language': 'भाषा',
    'settings.theme': 'थीम',
    'settings.theme.light': 'लाइट',
    'settings.theme.dark': 'डार्क',
    'login.title': 'तुमच्या खात्यात लॉग इन करा',
    'login.username': 'वापरकर्तानाव',
    'login.password': 'पासवर्ड',
    'login.rememberMe': 'मला लक्षात ठेवा',
    'login.button': 'लॉग इन करा',
    'login.error': 'अवैध वापरकर्तानाव किंवा पासवर्ड.',
    'settings.logout': 'लॉग आउट',
    'settings.logout.confirm': 'तुम्हाला नक्की लॉग आउट करायचे आहे का?',
  },
};

export const STATUS_COLORS: Record<OrderStatus, string> = {
  [OrderStatus.New]: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200',
  [OrderStatus.InProgress]: 'bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200',
  [OrderStatus.Completed]: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200',
  [OrderStatus.Delivered]: 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200',
  [OrderStatus.Cancelled]: 'bg-gray-200 text-gray-800 dark:bg-gray-700 dark:text-gray-200',
};

export const INITIAL_GARMENT_TYPES: GarmentTypeDefinition[] = [
    { name: 'Blouse', measurementFields: ['length', 'shoulder', 'bust', 'waist', 'sleeveLength', 'armhole', 'frontNeck', 'backNeck'] },
    { name: 'Kurti', measurementFields: ['length', 'shoulder', 'bust', 'waist', 'hip', 'sleeveLength', 'armhole'] },
    { name: 'Salwar Suit', measurementFields: ['topLength', 'bottomLength', 'bust', 'waist', 'hip', 'sleeveLength'] },
    { name: 'Lehenga', measurementFields: ['waist', 'length', 'flair'] },
    { name: 'Gown', measurementFields: ['length', 'shoulder', 'bust', 'waist', 'hip', 'sleeveLength', 'flair'] },
    { name: 'Saree', measurementFields: ['fall', 'pico', 'blousePieceCut'] },
    { name: 'Dress', measurementFields: ['length', 'shoulder', 'bust', 'waist', 'hip', 'sleeveLength'] },
];


// MOCK DATA
const MOCK_CUSTOMERS: Customer[] = [
  { id: 'C1', fullName: 'Priya Sharma', phone: '9876543210', address: '123, Rose Villa, Mumbai', createdAt: new Date().toISOString() },
  { id: 'C2', fullName: 'Anjali Verma', phone: '8765432109', address: '45, Sunshine Apts, Pune', createdAt: new Date().toISOString() },
];

const MOCK_EMPLOYEES: Employee[] = [
  { id: 'E1', name: 'Ramesh Kumar', role: 'Cutter', createdAt: new Date().toISOString(), payments: [], phone: '9112233445' },
  { id: 'E2', name: 'Sita Devi', role: 'Stitcher', createdAt: new Date().toISOString(), payments: [], phone: '9223344556' },
  { id: 'E3', name: 'Geeta Singh', role: 'Stitcher', createdAt: new Date().toISOString(), payments: [], phone: '9334455667' },
];

const MOCK_MEASUREMENTS: Measurement[] = [
  { id: 'M1', customerId: 'C1', garmentType: 'Blouse', measurements: { length: 14, shoulder: 15, bust: 36, waist: 30, sleeveLength: 5, armhole: 16, frontNeck: 7, backNeck: 9 }, createdAt: new Date().toISOString() },
  { id: 'M2', customerId: 'C2', garmentType: 'Kurti', measurements: { length: 42, shoulder: 15.5, bust: 38, waist: 34, hip: 40, sleeveLength: 18, armhole: 17 }, createdAt: new Date().toISOString() },
];

const MOCK_LINE_ITEMS: LineItem[] = [
    { id: 'L1', garmentType: 'Blouse', quantity: 1, unitPrice: 800, fabricSource: 'Customer', measurementSnapshot: MOCK_MEASUREMENTS[0].measurements, assignments: [{ id: 'L1-A1', employeeId: 'E2', payment: 300 }] },
    { id: 'L2', garmentType: 'Kurti', quantity: 2, unitPrice: 1200, fabricSource: 'Shop', measurementSnapshot: MOCK_MEASUREMENTS[1].measurements, assignments: [{ id: 'L2-A1', employeeId: 'E3', payment: 450 }, { id: 'L2-A2', employeeId: 'E2', payment: 450 }] },
];

const MOCK_PAYMENTS: Payment[] = [
    { id: 'P1', amount: 500, method: 'UPI', date: new Date().toISOString() }
];

const MOCK_ORDERS: Order[] = [
  { id: 'O1', orderNumber: 'DT-20240520-0001', customerId: 'C1', orderDate: '2024-05-20T10:00:00Z', dueDate: '2024-05-30T18:00:00Z', status: OrderStatus.InProgress, items: [MOCK_LINE_ITEMS[0]], subtotal: 800, discount: 0, total: 800, advance: 300, payments: [{...MOCK_PAYMENTS[0], amount: 300}], balance: 500 },
  { id: 'O2', orderNumber: 'DT-20240521-0002', customerId: 'C2', orderDate: '2024-05-21T11:00:00Z', dueDate: '2024-06-05T18:00:00Z', status: OrderStatus.InProgress, items: [MOCK_LINE_ITEMS[1]], subtotal: 2400, discount: 100, total: 2300, advance: 1000, payments: [], balance: 2300 },
  { id: 'O3', orderNumber: 'DT-20240515-0003', customerId: 'C1', orderDate: '2024-05-15T14:00:00Z', dueDate: '2024-05-25T18:00:00Z', status: OrderStatus.Completed, items: [{...MOCK_LINE_ITEMS[0], unitPrice: 750, assignments: [{id: 'L1-A1', employeeId: 'E2', payment: 280}] }], subtotal: 750, discount: 0, total: 750, advance: 750, payments: [{...MOCK_PAYMENTS[0], amount: 750}], balance: 0 },
];

const MOCK_SHOP_INFO: ShopInfo = {
    name: "Deepak Tailor",
    tagline: "Ladies Specialists",
    address: "Nathbaba galli , nathbaba madir, jalna",
    phone: "9123456789"
};


export const MOCK_INITIAL_STATE = {
    language: 'en' as const,
    theme: 'light' as const,
    customers: MOCK_CUSTOMERS,
    measurements: MOCK_MEASUREMENTS,
    orders: MOCK_ORDERS,
    garmentTypes: INITIAL_GARMENT_TYPES,
    employees: MOCK_EMPLOYEES,
    isAuthenticated: false,
    shopInfo: MOCK_SHOP_INFO,
}
